# Generated by Django 5.1.4 on 2024-12-11 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(help_text='ФИО', max_length=100, verbose_name='ФИО')),
                ('date', models.DateField(help_text='Дата рождения', verbose_name='Дата рождения')),
                ('create', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('author', models.ForeignKey(help_text='Имя автора', on_delete=django.db.models.deletion.CASCADE, related_name='birthday', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Дата', verbose_name='Дата')),
                ('full_name', models.TextField(help_text='ФИО Организация Должность', max_length=70, verbose_name='ФИО Организация Должность')),
                ('question', models.TextField(help_text='Суть вопроса', max_length=200, verbose_name='Вопрос')),
                ('telephone', models.TextField(help_text='Телефон', max_length=15, verbose_name='Телефон')),
                ('result', models.TextField(help_text='Итог', max_length=200, verbose_name='Итог')),
                ('create', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('author', models.ForeignKey(help_text='Имя автора', on_delete=django.db.models.deletion.CASCADE, related_name='call', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(help_text='ФИО', max_length=100, verbose_name='ФИО')),
                ('other', models.TextField(help_text='Дополнительно', max_length=200, verbose_name='Дополнительно')),
                ('create', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('author', models.ForeignKey(help_text='Имя автора', on_delete=django.db.models.deletion.CASCADE, related_name='reception', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
