# Generated by Django 5.1.4 on 2024-12-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'verbose_name': 'день рождения', 'verbose_name_plural': 'дни рождения'},
        ),
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ('date',), 'verbose_name': 'Звонок', 'verbose_name_plural': 'Звонки'},
        ),
        migrations.AlterModelOptions(
            name='reception',
            options={'verbose_name': 'посещение', 'verbose_name_plural': 'посещения'},
        ),
    ]
