# Generated by Django 5.1.4 on 2024-12-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_birthday_options_alter_call_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='date',
            field=models.DateField(blank=True, help_text='Дата рождения', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='call',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Дата', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='call',
            name='question',
            field=models.TextField(blank=True, help_text='Суть вопроса', max_length=200, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='call',
            name='telephone',
            field=models.TextField(blank=True, help_text='Телефон', max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='other',
            field=models.TextField(blank=True, help_text='Дополнительно', max_length=200, null=True, verbose_name='Дополнительно'),
        ),
    ]
