# Generated by Django 5.1.4 on 2024-12-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_call_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='author',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='create',
        ),
        migrations.RemoveField(
            model_name='call',
            name='author',
        ),
        migrations.RemoveField(
            model_name='call',
            name='create',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='create',
        ),
    ]
