# Generated by Django 5.1.4 on 2024-12-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_birthday_author_remove_birthday_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='question',
            field=models.TextField(blank=True, help_text='Вопрос', max_length=200, null=True, verbose_name='Вопрос'),
        ),
    ]
